# PVTT Test 01: Watch to Bracelet
# Jewelry category - Personalized wood watch to engraved bracelet

video:
    video_path: ../../data/pvtt-benchmark/videos/jewelry/JEWE001.mp4
    source_prompt: A personalized ebony wood watch with engraved details, elegant men's wrist watch displayed on a white background.
    target_prompt: A personalized engraved bar bracelet with curved nameplate, elegant slider bracelet displayed on a white background.
    source_blend: watch
    target_blend: bracelet

infernece:
    num_inference_step: 50

training-free-type:
    flag_flowedit: False
    flag_flowalign: True

flowedit:
    strength: 0.7
    target_guidance_scale: 13.5
    source_guidance_scale: 5.0
    save_video: ./results/pvtt/test01_flowedit_watch_to_bracelet.mp4

flowalign:
    strength: 0.7
    target_guidance_scale: 19.5
    flag_attnmask: True
    zeta_scale: 1e-3
    bg_zeta_scale: 1e-3
    save_video: ./results/pvtt/test01_flowalign_watch_to_bracelet.mp4
